-- ========================================
-- CREAR TABLAS
-- ========================================

-- Tabla UNITS
CREATE TABLE UNITS (
    ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Tabla SHIFTS
CREATE TABLE SHIFTS (
    ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    START_TIME VARCHAR2(5) NOT NULL, -- Format: HH:MM
    END_TIME VARCHAR2(5) NOT NULL,   -- Format: HH:MM
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Tabla PATIENTS
CREATE TABLE PATIENTS (
    ID VARCHAR2(50) PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    UNIT_ID VARCHAR2(50) NOT NULL,
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(20), -- Male, Female, Other, Unknown
    ADMISSION_DATE TIMESTAMP,
    ROOM_NUMBER VARCHAR2(20),
    DIAGNOSIS VARCHAR2(500),
    ALLERGIES VARCHAR2(1000),
    MEDICATIONS VARCHAR2(1000),
    NOTES VARCHAR2(1000),
    MRN VARCHAR2(20), -- Medical Record Number
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PATIENTS_UNIT FOREIGN KEY (UNIT_ID) REFERENCES UNITS(ID)
);

-- Tabla USER_ASSIGNMENTS (para asignaciones de pacientes a usuarios)
CREATE TABLE USER_ASSIGNMENTS (
    ASSIGNMENT_ID VARCHAR2(255) PRIMARY KEY,
    USER_ID VARCHAR2(255) NOT NULL,
    SHIFT_ID VARCHAR2(50) NOT NULL,
    PATIENT_ID VARCHAR2(50) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ASSIGNMENTS_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(ID),
    CONSTRAINT FK_ASSIGNMENTS_SHIFT FOREIGN KEY (SHIFT_ID) REFERENCES SHIFTS(ID)
);

-- Tabla CONTRIBUTORS (para funcionalidad existente)
CREATE TABLE CONTRIBUTORS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    EMAIL VARCHAR2(200) NOT NULL,
    PHONE_NUMBER VARCHAR2(20),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Tabla HANDOVERS
CREATE TABLE HANDOVERS (
    ID VARCHAR2(50) PRIMARY KEY,
    ASSIGNMENT_ID VARCHAR2(255) NOT NULL, -- FK a USER_ASSIGNMENTS
    PATIENT_ID VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'Draft', -- Legacy field, state determined by timestamp fields (Draft, Ready, InProgress, Accepted, Completed, Cancelled, Rejected, Expired)
    ILLNESS_SEVERITY VARCHAR2(20), -- Stable, Watcher, Unstable, Critical
    PATIENT_SUMMARY CLOB,
    SITUATION_AWARENESS_DOC_ID VARCHAR2(100),
    SYNTHESIS CLOB,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    SHIFT_NAME VARCHAR2(100),
    FROM_SHIFT_ID VARCHAR2(50), -- Shift being handed over FROM
    TO_SHIFT_ID VARCHAR2(50), -- Shift receiving the handover TO
    FROM_DOCTOR_ID VARCHAR2(255), -- Doctor handing over (Clerk User ID)
    TO_DOCTOR_ID VARCHAR2(255), -- Doctor receiving handover (Clerk User ID)
    RECEIVER_USER_ID VARCHAR2(255), -- Doctor receiving handover (Clerk User ID)
    CREATED_BY VARCHAR2(255), -- Clerk User ID who initiated
    INITIATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, -- When handover was initiated
    ACCEPTED_AT TIMESTAMP, -- When receiving doctor accepted
    COMPLETED_BY VARCHAR2(255), -- Who completed the handover
    READY_AT         TIMESTAMP,
    STARTED_AT       TIMESTAMP,
    ACKNOWLEDGED_AT  TIMESTAMP, -- Optional: when receiver acknowledges seeing the handover
    CANCELLED_AT     TIMESTAMP,
    REJECTED_AT      TIMESTAMP,
    REJECTION_REASON VARCHAR2(4000),
    EXPIRED_AT       TIMESTAMP,
    HANDOVER_TYPE    VARCHAR2(30),
    HANDOVER_WINDOW_DATE DATE, -- día/ventana del cambio
    CONSTRAINT FK_HANDOVERS_ASSIGNMENT FOREIGN KEY (ASSIGNMENT_ID) REFERENCES USER_ASSIGNMENTS(ASSIGNMENT_ID),
    CONSTRAINT FK_HANDOVERS_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(ID),
    CONSTRAINT FK_HANDOVERS_FROM_SHIFT FOREIGN KEY (FROM_SHIFT_ID) REFERENCES SHIFTS(ID),
    CONSTRAINT FK_HANDOVERS_TO_SHIFT FOREIGN KEY (TO_SHIFT_ID) REFERENCES SHIFTS(ID),
    CONSTRAINT chk_handover_type CHECK (HANDOVER_TYPE IN ('ShiftToShift','TemporaryCoverage','Consult'))
);

-- Tabla HANDOVER_ACTION_ITEMS
CREATE TABLE HANDOVER_ACTION_ITEMS (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    IS_COMPLETED NUMBER(1) DEFAULT 0, -- 0 = false, 1 = true
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    CONSTRAINT FK_ACTION_ITEMS_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID)
);

-- Tabla HANDOVER_PARTICIPANTS (participantes activos en un handover)
CREATE TABLE HANDOVER_PARTICIPANTS (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(255) NOT NULL, -- Clerk User ID
    USER_NAME VARCHAR2(200) NOT NULL,
    USER_ROLE VARCHAR2(100),
    STATUS VARCHAR2(20) DEFAULT 'active', -- active, inactive, viewing
    JOINED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_ACTIVITY TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_PARTICIPANTS_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID)
);

-- Tabla HANDOVER_SECTIONS (secciones I-PASS individuales)
CREATE TABLE HANDOVER_SECTIONS (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50) NOT NULL,
    SECTION_TYPE VARCHAR2(20) NOT NULL, -- illness_severity, patient_summary, action_items, situation_awareness, synthesis
    CONTENT CLOB,
    STATUS VARCHAR2(20) DEFAULT 'draft', -- draft, in_progress, completed
    LAST_EDITED_BY VARCHAR2(255), -- Clerk User ID
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_SECTIONS_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID)
);


-- Tabla SYNC_STATUS (estado de sincronización del handover)
CREATE TABLE HANDOVER_SYNC_STATUS (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(255) NOT NULL, -- Clerk User ID
    SYNC_STATUS VARCHAR2(20) DEFAULT 'synced', -- synced, syncing, pending, offline, error
    LAST_SYNC TIMESTAMP DEFAULT SYSTIMESTAMP,
    VERSION NUMBER DEFAULT 1,
    CONSTRAINT FK_SYNC_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID),
    CONSTRAINT UK_SYNC_USER_HANDOVER UNIQUE (HANDOVER_ID, USER_ID)
);

-- Tabla USERS (información de usuarios de Clerk)
CREATE TABLE USERS (
    ID VARCHAR2(255) PRIMARY KEY, -- Clerk User ID
    EMAIL VARCHAR2(200) NOT NULL,
    FIRST_NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100),
    FULL_NAME VARCHAR2(200),
    AVATAR_URL VARCHAR2(500),
    ROLE VARCHAR2(50) DEFAULT 'user', -- admin, doctor, nurse, etc.
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    LAST_LOGIN TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Add foreign key constraints for HANDOVERS table (after USERS table is created)
ALTER TABLE HANDOVERS ADD CONSTRAINT FK_HANDOVERS_FROM_DOCTOR FOREIGN KEY (FROM_DOCTOR_ID) REFERENCES USERS(ID);
ALTER TABLE HANDOVERS ADD CONSTRAINT FK_HANDOVERS_TO_DOCTOR FOREIGN KEY (TO_DOCTOR_ID) REFERENCES USERS(ID);
ALTER TABLE HANDOVERS ADD CONSTRAINT FK_HANDOVERS_COMPLETED_BY FOREIGN KEY (COMPLETED_BY) REFERENCES USERS(ID);
ALTER TABLE HANDOVERS ADD CONSTRAINT FK_HANDOVERS_RECEIVER FOREIGN KEY (RECEIVER_USER_ID) REFERENCES USERS(ID);

-- Tabla PATIENT_SUMMARIES (resúmenes independientes de pacientes)
CREATE TABLE PATIENT_SUMMARIES (
    ID VARCHAR2(50) PRIMARY KEY,
    PATIENT_ID VARCHAR2(50) NOT NULL,
    PHYSICIAN_ID VARCHAR2(255) NOT NULL, -- Clerk User ID del médico asignado
    SUMMARY_TEXT CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_EDITED_BY VARCHAR2(255), -- Clerk User ID de quien editó por última vez
    CONSTRAINT FK_PATIENT_SUMMARIES_PATIENT FOREIGN KEY (PATIENT_ID) REFERENCES PATIENTS(ID),
    CONSTRAINT FK_PATIENT_SUMMARIES_PHYSICIAN FOREIGN KEY (PHYSICIAN_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_PATIENT_SUMMARIES_EDITOR FOREIGN KEY (LAST_EDITED_BY) REFERENCES USERS(ID)
);

-- Tabla USER_PREFERENCES (preferencias de usuario)
CREATE TABLE USER_PREFERENCES (
    ID VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(255) NOT NULL,
    THEME VARCHAR2(20) DEFAULT 'light',
    LANGUAGE VARCHAR2(10) DEFAULT 'en',
    TIMEZONE VARCHAR2(50) DEFAULT 'UTC',
    NOTIFICATIONS_ENABLED NUMBER(1) DEFAULT 1,
    AUTO_SAVE_ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_USER_PREFERENCES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- Tabla USER_SESSIONS (sesiones activas de usuario)
CREATE TABLE USER_SESSIONS (
    ID VARCHAR2(50) PRIMARY KEY,
    USER_ID VARCHAR2(255) NOT NULL,
    SESSION_START TIMESTAMP DEFAULT SYSTIMESTAMP,
    SESSION_END TIMESTAMP,
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT VARCHAR2(500),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_USER_SESSIONS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- Tabla HANDOVER_CHECKLISTS (listas de verificación para síntesis)
CREATE TABLE HANDOVER_CHECKLISTS (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(255) NOT NULL,
    ITEM_ID VARCHAR2(100) NOT NULL,
    ITEM_CATEGORY VARCHAR2(100),
    ITEM_LABEL VARCHAR2(500),
    ITEM_DESCRIPTION VARCHAR2(1000),
    IS_REQUIRED NUMBER(1) DEFAULT 0,
    IS_CHECKED NUMBER(1) DEFAULT 0,
    CHECKED_AT TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CHECKLIST_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID),
    CONSTRAINT FK_CHECKLIST_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT UK_CHECKLIST_ITEM UNIQUE (HANDOVER_ID, USER_ID, ITEM_ID)
);

-- Tabla HANDOVER_CONTINGENCY (planes de contingencia)
CREATE TABLE HANDOVER_CONTINGENCY (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50) NOT NULL,
    CONDITION_TEXT VARCHAR2(1000) NOT NULL,
    ACTION_TEXT VARCHAR2(1000) NOT NULL,
    PRIORITY VARCHAR2(20) DEFAULT 'medium', -- low, medium, high
    STATUS VARCHAR2(20) DEFAULT 'active', -- active, planned, completed
    CREATED_BY VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_CONTINGENCY_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID),
    CONSTRAINT FK_CONTINGENCY_USER FOREIGN KEY (CREATED_BY) REFERENCES USERS(ID)
);

-- Tabla HANDOVER_MESSAGES (mensajes de discusión)
CREATE TABLE HANDOVER_MESSAGES (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50) NOT NULL,
    USER_ID VARCHAR2(255) NOT NULL,
    MESSAGE_TEXT CLOB NOT NULL,
    MESSAGE_TYPE VARCHAR2(20) DEFAULT 'message', -- message, system, notification
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_DISCUSSION_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID),
    CONSTRAINT FK_DISCUSSION_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

-- Tabla HANDOVER_MENTIONS (menciones en mensajes)
CREATE TABLE HANDOVER_MENTIONS (
    ID VARCHAR2(50) PRIMARY KEY,
    MESSAGE_ID VARCHAR2(50) NOT NULL,
    MENTIONED_USER_ID VARCHAR2(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_MENTION_MESSAGE FOREIGN KEY (MESSAGE_ID) REFERENCES HANDOVER_MESSAGES(ID),
    CONSTRAINT FK_MENTION_USER FOREIGN KEY (MENTIONED_USER_ID) REFERENCES USERS(ID)
);

-- Tabla IPASS_TEMPLATES (plantillas I-PASS)
CREATE TABLE IPASS_TEMPLATES (
    ID VARCHAR2(50) PRIMARY KEY,
    TEMPLATE_ID VARCHAR2(100) NOT NULL,
    SECTION VARCHAR2(50) NOT NULL, -- illness, patient, actions, awareness, synthesis
    TITLE VARCHAR2(200) NOT NULL,
    TEMPLATE_CONTENT CLOB NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_TEMPLATE_ID UNIQUE (TEMPLATE_ID)
);

-- Tabla SECTION_TEMPLATES (plantillas de secciones)
CREATE TABLE SECTION_TEMPLATES (
    ID VARCHAR2(50) PRIMARY KEY,
    SECTION_TYPE VARCHAR2(50) NOT NULL, -- patient_summary, situation_awareness, synthesis
    TEMPLATE_NAME VARCHAR2(200) NOT NULL,
    TEMPLATE_CONTENT CLOB NOT NULL,
    IS_DEFAULT NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Tabla HANDOVER_ACTIVITY_LOG (registro de actividades)
CREATE TABLE HANDOVER_ACTIVITY_LOG (
    ID VARCHAR2(50) PRIMARY KEY,
    HANDOVER_ID VARCHAR2(50),
    USER_ID VARCHAR2(255),
    ACTIVITY_TYPE VARCHAR2(100) NOT NULL, -- edited_section, added_action_item, sent_message, etc.
    ACTIVITY_DESCRIPTION VARCHAR2(500),
    SECTION_AFFECTED VARCHAR2(50),
    METADATA CLOB, -- JSON with additional activity data
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_ACTIVITY_HANDOVER FOREIGN KEY (HANDOVER_ID) REFERENCES HANDOVERS(ID),
    CONSTRAINT FK_ACTIVITY_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

