-- ========================================
-- CREAR ÍNDICES
-- ========================================

CREATE INDEX IDX_PATIENTS_UNIT_ID ON PATIENTS(UNIT_ID);
CREATE INDEX IDX_USER_ASSIGNMENTS_USER ON USER_ASSIGNMENTS(USER_ID);
CREATE INDEX IDX_USER_ASSIGNMENTS_PATIENT ON USER_ASSIGNMENTS(PATIENT_ID);
CREATE INDEX IDX_USER_ASSIGNMENTS_SHIFT ON USER_ASSIGNMENTS(SHIFT_ID);
CREATE INDEX IDX_HANDOVERS_PATIENT_ID ON HANDOVERS(PATIENT_ID);
CREATE INDEX IDX_HANDOVERS_ASSIGNMENT_ID ON HANDOVERS(ASSIGNMENT_ID);
CREATE INDEX IDX_HANDOVERS_STATUS ON HANDOVERS(STATUS);
CREATE INDEX IDX_HANDOVERS_CREATED_BY ON HANDOVERS(CREATED_BY);
CREATE INDEX IDX_HANDOVERS_FROM_DOCTOR ON HANDOVERS(FROM_DOCTOR_ID);
CREATE INDEX IDX_HANDOVERS_TO_DOCTOR ON HANDOVERS(TO_DOCTOR_ID);
CREATE INDEX IDX_HANDOVERS_FROM_SHIFT ON HANDOVERS(FROM_SHIFT_ID);
CREATE INDEX IDX_HANDOVERS_TO_SHIFT ON HANDOVERS(TO_SHIFT_ID);
CREATE INDEX IDX_HANDOVERS_INITIATED_AT ON HANDOVERS(INITIATED_AT);
CREATE INDEX IDX_HANDOVERS_COMPLETED_AT ON HANDOVERS(COMPLETED_AT);
CREATE INDEX IDX_HACTION_HANDOVER_ID ON HANDOVER_ACTION_ITEMS(HANDOVER_ID);
CREATE INDEX IDX_PARTICIPANTS_HANDOVER_ID ON HANDOVER_PARTICIPANTS(HANDOVER_ID);
CREATE INDEX IDX_PARTICIPANTS_USER_ID ON HANDOVER_PARTICIPANTS(USER_ID);
CREATE INDEX IDX_PARTICIPANTS_STATUS ON HANDOVER_PARTICIPANTS(STATUS);
CREATE INDEX IDX_SECTIONS_HANDOVER_ID ON HANDOVER_SECTIONS(HANDOVER_ID);
CREATE INDEX IDX_SECTIONS_TYPE ON HANDOVER_SECTIONS(SECTION_TYPE);
CREATE INDEX IDX_SECTIONS_STATUS ON HANDOVER_SECTIONS(STATUS);
CREATE INDEX IDX_PAT_SUMMARIES_PATIENT ON PATIENT_SUMMARIES(PATIENT_ID);
CREATE INDEX IDX_PAT_SUMMARIES_PHYSICIAN ON PATIENT_SUMMARIES(PHYSICIAN_ID);
CREATE INDEX IDX_PAT_SUMMARIES_CREATED ON PATIENT_SUMMARIES(CREATED_AT);
CREATE INDEX IDX_PAT_SUMMARIES_UPDATED ON PATIENT_SUMMARIES(UPDATED_AT);
CREATE INDEX IDX_SYNC_HANDOVER_ID ON HANDOVER_SYNC_STATUS(HANDOVER_ID);
CREATE INDEX IDX_SYNC_USER_ID ON HANDOVER_SYNC_STATUS(USER_ID);
CREATE INDEX IDX_SYNC_STATUS ON HANDOVER_SYNC_STATUS(SYNC_STATUS);
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE);
CREATE INDEX IDX_USERS_IS_ACTIVE ON USERS(IS_ACTIVE);
CREATE INDEX IDX_USER_PREFERENCES_USER_ID ON USER_PREFERENCES(USER_ID);
CREATE INDEX IDX_USER_SESSIONS_USER_ID ON USER_SESSIONS(USER_ID);
CREATE INDEX IDX_USER_SESSIONS_ACTIVE ON USER_SESSIONS(IS_ACTIVE);
CREATE INDEX IDX_CHECKLIST_HANDOVER ON HANDOVER_CHECKLISTS(HANDOVER_ID);
CREATE INDEX IDX_CHECKLIST_USER ON HANDOVER_CHECKLISTS(USER_ID);
CREATE INDEX IDX_CHECKLIST_ITEM ON HANDOVER_CHECKLISTS(ITEM_ID);
CREATE INDEX IDX_CHECKLIST_CHECKED ON HANDOVER_CHECKLISTS(IS_CHECKED);
CREATE INDEX IDX_CONTINGENCY_HANDOVER ON HANDOVER_CONTINGENCY(HANDOVER_ID);
CREATE INDEX IDX_CONTINGENCY_USER ON HANDOVER_CONTINGENCY(CREATED_BY);
CREATE INDEX IDX_CONTINGENCY_STATUS ON HANDOVER_CONTINGENCY(STATUS);
CREATE INDEX IDX_DISCUSSION_HANDOVER ON HANDOVER_MESSAGES(HANDOVER_ID);
CREATE INDEX IDX_DISCUSSION_USER ON HANDOVER_MESSAGES(USER_ID);
CREATE INDEX IDX_DISCUSSION_TYPE ON HANDOVER_MESSAGES(MESSAGE_TYPE);
CREATE INDEX IDX_DISCUSSION_CREATED ON HANDOVER_MESSAGES(CREATED_AT);
CREATE INDEX IDX_MENTION_MESSAGE ON HANDOVER_MENTIONS(MESSAGE_ID);
CREATE INDEX IDX_MENTION_USER ON HANDOVER_MENTIONS(MENTIONED_USER_ID);
-- Note: IDX_IPASS_TEMPLATE_ID index not needed as UK_TEMPLATE_ID unique constraint creates it automatically
CREATE INDEX IDX_IPASS_SECTION ON IPASS_TEMPLATES(SECTION);
CREATE INDEX IDX_IPASS_ACTIVE ON IPASS_TEMPLATES(IS_ACTIVE);
CREATE INDEX IDX_SECTION_TEMPLATE_TYPE ON SECTION_TEMPLATES(SECTION_TYPE);
CREATE INDEX IDX_SECTION_TEMPLATE_DEFAULT ON SECTION_TEMPLATES(IS_DEFAULT);
CREATE INDEX IDX_ACTIVITY_HANDOVER ON HANDOVER_ACTIVITY_LOG(HANDOVER_ID);
CREATE INDEX IDX_ACTIVITY_USER ON HANDOVER_ACTIVITY_LOG(USER_ID);
CREATE INDEX IDX_ACTIVITY_TYPE ON HANDOVER_ACTIVITY_LOG(ACTIVITY_TYPE);
CREATE INDEX IDX_ACTIVITY_CREATED ON HANDOVER_ACTIVITY_LOG(CREATED_AT);

-- Índice único para asegurar un solo handover activo por ventana de traspaso
CREATE UNIQUE INDEX UQ_ACTIVE_HANDOVER_WINDOW
ON HANDOVERS (
  PATIENT_ID,
  HANDOVER_WINDOW_DATE,
  FROM_SHIFT_ID,
  TO_SHIFT_ID,
  CASE
    WHEN COMPLETED_AT IS NULL
     AND CANCELLED_AT IS NULL
     AND REJECTED_AT  IS NULL
     AND EXPIRED_AT   IS NULL
    THEN 1
    ELSE NULL
  END
);

