-- ========================================
-- CONSULTAS DE VERIFICACIÓN
-- ========================================

-- Connect as RELEVO_APP user
CONNECT RELEVO_APP/TuPass123;

-- Verificar conteos de tablas
SELECT 'UNITS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM UNITS
UNION ALL
SELECT 'SHIFTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM SHIFTS
UNION ALL
SELECT 'PATIENTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM PATIENTS
UNION ALL
SELECT 'USER_ASSIGNMENTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM USER_ASSIGNMENTS
UNION ALL
SELECT 'CONTRIBUTORS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM CONTRIBUTORS
UNION ALL
SELECT 'HANDOVERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVERS
UNION ALL
SELECT 'VW_HANDOVERS_STATE' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM VW_HANDOVERS_STATE
UNION ALL
SELECT 'HANDOVER_ACTION_ITEMS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_ACTION_ITEMS
UNION ALL
SELECT 'HANDOVER_PARTICIPANTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_PARTICIPANTS
UNION ALL
-- HANDOVER_SECTIONS table removed as part of migration to singleton tables
SELECT 'PATIENT_SUMMARIES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM PATIENT_SUMMARIES
UNION ALL
SELECT 'HANDOVER_SYNC_STATUS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_SYNC_STATUS
UNION ALL
SELECT 'USERS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM USERS
UNION ALL
SELECT 'USER_PREFERENCES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM USER_PREFERENCES
UNION ALL
SELECT 'USER_SESSIONS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM USER_SESSIONS
UNION ALL
SELECT 'HANDOVER_CHECKLISTS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_CHECKLISTS
UNION ALL
SELECT 'HANDOVER_CONTINGENCY' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_CONTINGENCY
UNION ALL
SELECT 'HANDOVER_MESSAGES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_MESSAGES
UNION ALL
SELECT 'HANDOVER_MENTIONS' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_MENTIONS
UNION ALL
SELECT 'IPASS_TEMPLATES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM IPASS_TEMPLATES
UNION ALL
SELECT 'SECTION_TEMPLATES' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM SECTION_TEMPLATES
UNION ALL
SELECT 'HANDOVER_ACTIVITY_LOG' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM HANDOVER_ACTIVITY_LOG
-- Singleton tables are now included in the main table creation

-- Inserción de datos de ejemplo
