# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host=https://localhost
@port=57679

// Assign patients to user
POST {{host}}:{{port}}/me/assignments
Content-Type: application/json

{
  "shiftId": "shift-day",
  "patientIds": ["pat-123", "pat-456"]
}

###

// Get my patients
GET {{host}}:{{port}}/me/patients

