/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteRouteImport } from './routes/_setup/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupShiftCheckInRouteImport } from './routes/_setup/shift-check-in'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedPatientPatientIdRouteImport } from './routes/_authenticated/patient.$patientId'
import { Route as AuthenticatedPatientPatientIdHistoryHandoverIdRouteImport } from './routes/_authenticated/patient.$patientId.history.$handoverId'

const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/_setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupShiftCheckInRoute = SetupShiftCheckInRouteImport.update({
  id: '/shift-check-in',
  path: '/shift-check-in',
  getParentRoute: () => SetupRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPatientPatientIdRoute =
  AuthenticatedPatientPatientIdRouteImport.update({
    id: '/patient/$patientId',
    path: '/patient/$patientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientPatientIdHistoryHandoverIdRoute =
  AuthenticatedPatientPatientIdHistoryHandoverIdRouteImport.update({
    id: '/history/$handoverId',
    path: '/history/$handoverId',
    getParentRoute: () => AuthenticatedPatientPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/shift-check-in': typeof SetupShiftCheckInRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRouteWithChildren
  '/patient/$patientId/history/$handoverId': typeof AuthenticatedPatientPatientIdHistoryHandoverIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/shift-check-in': typeof SetupShiftCheckInRoute
  '/patient/$patientId': typeof AuthenticatedPatientPatientIdRouteWithChildren
  '/patient/$patientId/history/$handoverId': typeof AuthenticatedPatientPatientIdHistoryHandoverIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_setup': typeof SetupRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_setup/shift-check-in': typeof SetupShiftCheckInRoute
  '/_authenticated/patient/$patientId': typeof AuthenticatedPatientPatientIdRouteWithChildren
  '/_authenticated/patient/$patientId/history/$handoverId': typeof AuthenticatedPatientPatientIdHistoryHandoverIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients'
    | '/shift-check-in'
    | '/patient/$patientId'
    | '/patient/$patientId/history/$handoverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/patients'
    | '/shift-check-in'
    | '/patient/$patientId'
    | '/patient/$patientId/history/$handoverId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_setup'
    | '/(auth)/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/patients'
    | '/_setup/shift-check-in'
    | '/_authenticated/patient/$patientId'
    | '/_authenticated/patient/$patientId/history/$handoverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SetupRouteRoute: typeof SetupRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_setup': {
      id: '/_setup'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_setup/shift-check-in': {
      id: '/_setup/shift-check-in'
      path: '/shift-check-in'
      fullPath: '/shift-check-in'
      preLoaderRoute: typeof SetupShiftCheckInRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/patient/$patientId': {
      id: '/_authenticated/patient/$patientId'
      path: '/patient/$patientId'
      fullPath: '/patient/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientPatientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/$patientId/history/$handoverId': {
      id: '/_authenticated/patient/$patientId/history/$handoverId'
      path: '/history/$handoverId'
      fullPath: '/patient/$patientId/history/$handoverId'
      preLoaderRoute: typeof AuthenticatedPatientPatientIdHistoryHandoverIdRouteImport
      parentRoute: typeof AuthenticatedPatientPatientIdRoute
    }
  }
}

interface AuthenticatedPatientPatientIdRouteChildren {
  AuthenticatedPatientPatientIdHistoryHandoverIdRoute: typeof AuthenticatedPatientPatientIdHistoryHandoverIdRoute
}

const AuthenticatedPatientPatientIdRouteChildren: AuthenticatedPatientPatientIdRouteChildren =
  {
    AuthenticatedPatientPatientIdHistoryHandoverIdRoute:
      AuthenticatedPatientPatientIdHistoryHandoverIdRoute,
  }

const AuthenticatedPatientPatientIdRouteWithChildren =
  AuthenticatedPatientPatientIdRoute._addFileChildren(
    AuthenticatedPatientPatientIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedPatientPatientIdRoute: typeof AuthenticatedPatientPatientIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedPatientPatientIdRoute:
    AuthenticatedPatientPatientIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SetupRouteRouteChildren {
  SetupShiftCheckInRoute: typeof SetupShiftCheckInRoute
}

const SetupRouteRouteChildren: SetupRouteRouteChildren = {
  SetupShiftCheckInRoute: SetupShiftCheckInRoute,
}

const SetupRouteRouteWithChildren = SetupRouteRoute._addFileChildren(
  SetupRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SetupRouteRoute: SetupRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
