/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedDailySetupRouteImport } from './routes/_authenticated/daily-setup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailySetupRoute = AuthenticatedDailySetupRouteImport.update({
  id: '/daily-setup',
  path: '/daily-setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof authLoginRoute
  '/daily-setup': typeof AuthenticatedDailySetupRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/daily-setup': typeof AuthenticatedDailySetupRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/daily-setup': typeof AuthenticatedDailySetupRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/daily-setup' | '/patients' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/daily-setup' | '/patients' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/daily-setup'
    | '/_authenticated/patients'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-setup': {
      id: '/_authenticated/daily-setup'
      path: '/daily-setup'
      fullPath: '/daily-setup'
      preLoaderRoute: typeof AuthenticatedDailySetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDailySetupRoute: typeof AuthenticatedDailySetupRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDailySetupRoute: AuthenticatedDailySetupRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
