
import type {
	Deployment,
	Project,
	RecentPreview,
	SearchResult,
} from "../components/home/types";

export const projects: Array<Project> = [
	{
		name: "relevo-app",
		url: "relevo-app.vercel.app",
		status: "Connect Git Repository",
		date: "Jul 12",
		icon: "react",
		hasGithub: false,
	},
	{
		name: "v0-portfolio-template-by-v0",
		url: "v0-portfolio-template-by-v0-mu-...",
		status: "Connect Git Repository",
		date: "Aug 17",
		icon: "react",
		hasGithub: false,
	},
	{
		name: "heroes-app",
		url: "No Production Deployment",
		status: "Create deploy.yml",
		date: "2/22/21",
		branch: "master",
		github: "LuisCusihuaman/Hero...",
		icon: "react",
		hasGithub: true,
	},
	{
		name: "calendar-app",
		url: "No Production Deployment",
		status: "docs: README.md",
		date: "8/8/20",
		branch: "master",
		github: "LuisCusihuaman/Cale...",
		icon: "react",
		hasGithub: true,
	},
	{
		name: "psa-frontend",
		url: "psa-frontend-alpha.vercel.app",
		status: "Connect Git Repository",
		date: "6/30/24",
		icon: "react",
		hasGithub: false,
	},
	{
		name: "image-component",
		url: "image-component-sandy-three.v...",
		status: "Initial commit",
		date: "2/5/21",
		branch: "master",
		github: "LuisCusihuaman/ima...",
		icon: "react",
		hasGithub: true,
	},
	{
		name: "v0-music-game-concept",
		url: "v0-music-game-concept.vercel.a...",
		status: "Connect Git Repository",
		date: "Mar 25",
		icon: "react",
		hasGithub: false,
	},
	{
		name: "backoffice",
		url: "backoffice-pi-dusky.vercel.app",
		status: "Initial commit",
		date: "10/16/23",
		branch: "main",
		github: "LuisCusihuaman/bac...",
		icon: "vercel",
		hasGithub: true,
	},
];

export const recentPreviews: Array<RecentPreview> = [
	{
		title: "Nuevo paciente asignado",
		avatars: [
			{ src: null, fallback: "LC", bg: "bg-blue-500" },
			{ src: null, fallback: "JD", bg: "bg-green-500" },
		],
		status: "Source",
		pr: "#123",
		color: "Ready",
	},
	{
		title: "Severidad cambió a Crítico",
		avatars: [{ src: null, fallback: "SM", bg: "bg-purple-500" }],
		status: "Error",
		pr: "#124",
	},
	{
		title: "Nueva acción asignada",
		avatars: [
			{ src: null, fallback: "AB", bg: "bg-orange-500" },
			{ src: null, fallback: "CD", bg: "bg-pink-500" },
		],
		status: "Source",
		pr: "#125",
		color: "Ready",
	},
	{
		title: "Comentario en traspaso",
		avatars: [{ src: null, fallback: "LC", bg: "bg-blue-500" }],
		status: "Source",
		pr: "#126",
		color: "Ready",
	},
	{
		title: "Traspaso completado",
		avatars: [{ src: null, fallback: "JD", bg: "bg-green-500" }],
		status: "Source",
		pr: "#127",
		color: "Ready",
	},
];

export const deployments: Array<Deployment> = [
	{
		id: "CDMFQKRs",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "calendar-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "c5b235d",
		message: "chore(deps): bump dependencies",
		time: "2d ago",
		author: "dependabot[bot]",
		statusTime: "2s (2d ago)",
		environmentType: "Preview",
		avatar: "DB",
	},
	{
		id: "8LB4tSUAh",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "calendar-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "7d4dbb5",
		message: "chore(deps): bump dependencies",
		time: "3d ago",
		author: "dependabot[bot]",
		statusTime: "2s (3d ago)",
		environmentType: "Preview",
		avatar: "DB",
	},
	{
		id: "3L5k6ngCp",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "heroes-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "7a50c77",
		message: "chore(deps): bump dependencies",
		time: "Aug 6",
		author: "dependabot[bot]",
		statusTime: "4s (18d ago)",
		environmentType: "Preview",
		avatar: "DB",
	},
	{
		id: "GX6A8fhaZ",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "calendar-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "1348002",
		message: "chore(deps): bump dependencies",
		time: "Jul 17",
		author: "dependabot[bot]",
		statusTime: "4s (38d ago)",
		environmentType: "Preview",
		avatar: "DB",
	},
	{
		id: "6qYUWvuN3",
		status: "Ready",
		statusColor: "bg-green-500",
		environment: "Promoted",
		environmentColor: "text-gray-600",
		project: "relevo-app",
		projectIcon: {
			type: "text",
			value: "V",
			bg: "bg-purple-500",
			text: "text-white",
		},
		branch: "main",
		commit: "Current",
		message: "Production Rebuild of 8Td...",
		time: "Jul 12",
		author: "luiscusihuaman",
		statusTime: "29s (43d ago)",
		current: true,
		environmentType: "Production",
		avatar: "LC",
	},
	{
		id: "8TdfXLHgY",
		status: "Ready",
		statusColor: "bg-green-500",
		environment: "Staged",
		environmentColor: "text-gray-600",
		project: "relevo-app",
		projectIcon: {
			type: "text",
			value: "V",
			bg: "bg-purple-500",
			text: "text-white",
		},
		branch: "eduardoc/spanish",
		commit: "e78260a",
		message: "Enhance diabetes management...",
		time: "Jul 12",
		author: "luiscusihuaman",
		statusTime: "21s (43d ago)",
		environmentType: "Preview",
		avatar: "LC",
	},
];

export const searchResults: Array<SearchResult> = [
	{
		name: "eduardoc/spanish",
		category: "Latest Deployment",
		type: "deployment",
	},
	{ name: "main", category: "Latest Deployment", type: "deployment" },
	{ name: "Luis Cusihuaman's projects", category: "Team", type: "team" },
	{ name: "relevo-app", category: "Project", type: "project" },
	{ name: "Analytics", category: "Project", type: "project" },
	{
		name: '"visitors this week"',
		category: "Navigation Assistant",
		type: "assistant",
	},
];
