
import type {
	Deployment,
	Project,
	RecentPreview,
	SearchResult,
} from "../components/home/types";

export const projects: Array<Project> = [
	{
		name: "Ana Pérez",
		url: "relevo-app.vercel.app",
		status: "Iniciar traspaso",
		date: "Jul 12",
		icon: "R",
		hasGithub: false,
		unit: "UCI",
	},
	{
		name: "Juan Rodríguez",
		url: "v0-portfolio-template-by-v0-mu-...",
		status: "Iniciar traspaso",
		date: "Aug 17",
		icon: "V",
		hasGithub: false,
		unit: "Cardiología",
	},
	{
		name: "Carlos Gómez",
		url: "No Production Deployment",
		status: "Create deploy.yml",
		date: "2/22/21",
		branch: "master",
		github: "LuisCusihuaman/Hero...",
		icon: "H",
		hasGithub: true,
		unit: "Emergencia",
	},
	{
		name: "María García",
		url: "No Production Deployment",
		status: "docs: README.md",
		date: "8/8/20",
		branch: "master",
		github: "LuisCusihuaman/Cale...",
		icon: "C",
		hasGithub: true,
		unit: "Pediatría",
	},
	{
		name: "Laura Schmidt",
		url: "psa-frontend-alpha.vercel.app",
		status: "Iniciar traspaso",
		date: "6/30/24",
		icon: "P",
		hasGithub: false,
		unit: "UCI",
	},
	{
		name: "Pedro Martinez",
		url: "image-component-sandy-three.v...",
		status: "Initial commit",
		date: "2/5/21",
		branch: "master",
		github: "LuisCusihuaman/ima...",
		icon: "I",
		hasGithub: true,
		unit: "Radiología",
	},
	{
		name: "Sofía Rossi",
		url: "v0-music-game-concept.vercel.a...",
		status: "Iniciar traspaso",
		date: "Mar 25",
		icon: "M",
		hasGithub: false,
		unit: "Psiquiatría",
	},
	{
		name: "Martin Herrera",
		url: "backoffice-pi-dusky.vercel.app",
		status: "Initial commit",
		date: "10/16/23",
		branch: "main",
		github: "LuisCusihuaman/bac...",
		icon: "B",
		hasGithub: true,
		unit: "Administración",
	},
];

// Map de nombre técnico de app/repositorio a nombre del paciente
export const projectToPatientName: Record<string, string> = {
	"calendar-app": "Ana Pérez",
	"heroes-app": "Carlos Gómez",
	"relevo-app": "Laura Schmidt",
};

export const recentPreviews: Array<RecentPreview> = [
	{
		title: "Nuevo paciente asignado",
		avatars: [
			{ src: null, fallback: "LC", bg: "bg-blue-500" },
			{ src: null, fallback: "JD", bg: "bg-green-500" },
		],
		status: "Source",
		pr: "#123",
		color: "Ready",
	},
	{
		title: "Severidad cambió a Crítico",
		avatars: [{ src: null, fallback: "SM", bg: "bg-purple-500" }],
		status: "Error",
		pr: "#124",
	},
	{
		title: "Nueva acción asignada",
		avatars: [
			{ src: null, fallback: "AB", bg: "bg-orange-500" },
			{ src: null, fallback: "CD", bg: "bg-pink-500" },
		],
		status: "Source",
		pr: "#125",
		color: "Ready",
	},
	{
		title: "Comentario en traspaso",
		avatars: [{ src: null, fallback: "LC", bg: "bg-blue-500" }],
		status: "Source",
		pr: "#126",
		color: "Ready",
	},
	{
		title: "Traspaso completado",
		avatars: [{ src: null, fallback: "JD", bg: "bg-green-500" }],
		status: "Source",
		pr: "#127",
		color: "Ready",
	},
];

export const deployments: Array<Deployment> = [
	{
		id: "CDMFQKRs",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "calendar-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "c5b235d",
		message: "chore(deps): bump dependencies",
		time: "2d ago",
		author: "dependabot[bot]",
		statusTime: "2s (2d ago)",
		environmentType: "Preview",
		avatar: "DB",
		bedLabel: "302A",
		mrn: "892778",
	},
	{
		id: "8LB4tSUAh",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "calendar-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "7d4dbb5",
		message: "chore(deps): bump dependencies",
		time: "3d ago",
		author: "dependabot[bot]",
		statusTime: "2s (3d ago)",
		environmentType: "Preview",
		avatar: "DB",
		mrn: "12345678",
	},
	{
		id: "3L5k6ngCp",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "heroes-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "7a50c77",
		message: "chore(deps): bump dependencies",
		time: "Aug 6",
		author: "dependabot[bot]",
		statusTime: "4s (18d ago)",
		environmentType: "Preview",
		avatar: "DB",
		bedLabel: "217B",
	},
	{
		id: "GX6A8fhaZ",
		status: "Error",
		statusColor: "bg-red-500",
		environment: "Unexpected Error",
		environmentColor: "text-red-600",
		project: "calendar-app",
		projectIcon: {
			type: "emoji",
			value: "❄️",
			bg: "bg-blue-100",
		},
		branch: "dependabot/npm_and_yarn",
		commit: "1348002",
		message: "chore(deps): bump dependencies",
		time: "Jul 17",
		author: "dependabot[bot]",
		statusTime: "4s (38d ago)",
		environmentType: "Preview",
		avatar: "DB",
		mrn: "99887766",
	},
	{
		id: "6qYUWvuN3",
		status: "Ready",
		statusColor: "bg-green-500",
		environment: "Promoted",
		environmentColor: "text-gray-600",
		project: "relevo-app",
		projectIcon: {
			type: "text",
			value: "V",
			bg: "bg-purple-500",
			text: "text-white",
		},
		branch: "main",
		commit: "Current",
		message: "Production Rebuild of 8Td...",
		time: "Jul 12",
		author: "luiscusihuaman",
		statusTime: "29s (43d ago)",
		current: true,
		environmentType: "Production",
		avatar: "LC",
		bedLabel: "401C",
	},
	{
		id: "8TdfXLHgY",
		status: "Ready",
		statusColor: "bg-green-500",
		environment: "Staged",
		environmentColor: "text-gray-600",
		project: "relevo-app",
		projectIcon: {
			type: "text",
			value: "V",
			bg: "bg-purple-500",
			text: "text-white",
		},
		branch: "eduardoc/spanish",
		commit: "e78260a",
		message: "Enhance diabetes management...",
		time: "Jul 12",
		author: "luiscusihuaman",
		statusTime: "21s (43d ago)",
		environmentType: "Preview",
		avatar: "LC",
		mrn: "445566",
	},
];

export const searchResults: Array<SearchResult> = [
	// Pacientes
	{ name: "Ana Pérez", category: "Pacientes", type: "project" },
	{ name: "Juan Rodríguez", category: "Pacientes", type: "project" },
	{ name: "Carlos Gómez", category: "Pacientes", type: "project" },

	// Traspasos (mantiene el tipo 'deployment' para el punto verde)
	{ name: "Ana Pérez", category: "Traspasos", type: "deployment" },
	{ name: "Laura Schmidt", category: "Traspasos", type: "deployment" },

	// Acciones rápidas (acciones de comando)
	{ name: "Iniciar traspaso", category: "Acciones rápidas", type: "assistant" },
	{ name: "Añadir acción", category: "Acciones rápidas", type: "assistant" },
	{ name: "Marcar alerta crítica", category: "Acciones rápidas", type: "assistant" },
	{ name: "Abrir notificaciones", category: "Acciones rápidas", type: "assistant" },
	{ name: "Crear nota clínica", category: "Acciones rápidas", type: "assistant" },

	// Notas clínicas
	{ name: "Nota de Ana Pérez", category: "Notas clínicas", type: "assistant" },
	{ name: "Nota de Carlos Gómez", category: "Notas clínicas", type: "assistant" },

	// Unidades/Servicios
	{ name: "UCI", category: "Unidades/Servicios", type: "assistant" },
	{ name: "Emergencia", category: "Unidades/Servicios", type: "assistant" },

	// Personas/Equipo
	{ name: "Luis Cusihuaman", category: "Personas/Equipo", type: "team" },
];
